### PR TITLE
Experiments

### PR DESCRIPTION
**Pull request by dkrammer**
Added Experiment class and Trial class (Trial class is only a skeleton that I used for testing purposes, needs a ton of work still). Experiment class also far from complete. Also added necessary dependencies for testing in app gradle file, and created ExperimentTest test class for... testing... experiment class.

### CODE REVIEW

**Comment by dkrammer** [comment]
Oh also deleted all the Shape classes we added for the lab

**Comment by edenemilynan** [comment]
Did you use a different plugin for testing than the lab?

**Comment by dkrammer** [comment]
No, it's all the same as how they showed us to do it.

**Review by edenemilynan — APPROVED** [review]
Originally was questioning it because I had intent testing stuck in my head. Looks good though. One thing that might have to change (but I'll merge it because it won't break anything) is the testHideResults(). It looks unfinished/like no trials are added, so how can you test that they're hidden? But maybe I'm reading it wrong. Let me know.

**Comment by edenemilynan** [comment]
Merging what Duncan has for the experiment class/the skeleton of trials for testing.

**Comment by dkrammer** [comment]
Yeup I forgot to call the addTestTrials() method, my bad, I'll fix that. 

Also as a note, complete implementation and testing of the Experiment class and hiding/showing trials will have to wait until the User and Trial classes are finished so I can test whether trials can be hidden based on their user. It also isn't abstract as of this commit, which I'll change when I create the various experiment subclasses. Just so we're all on the same page where this is at right now. I mostly made the pull request so we could get rid of the extraneous classes and add in the testing dependencies, more than anything. Unless I'm forgetting something obvious any new branches should be set up properly and good to go now when checkout out from main.

**Comment by dkrammer** [comment]
Aaaah I forgot something obvious, I didn't put in robotium for intent testing >:(

**Pull request merged**
